type IComp is interface(in any channel)

component Comp presents IComp
{
	vbool = any(true)
	vint = any(-3)
	tunsigned = any($3)
	treal = any(3.2)
	tbyte = any(#10)
	tpointer = any("ohai")

	constructor()
	{
	}

	behaviour
	{
		receive types from channel
		project types as ttype onto
			bool: {}
			integer: {}
			unsigned: {}
			real: {}
			byte: {}
			string: {}
			default: {}
	}
}

comp1 = new Comp()
